### ISSUE TITLE
Repeater is not available in bintray?

### ISSUE THREAD

**Issue by blackknight467** [snowplow-incubator/snowplow-bigquery-loader#119]
I've been trying to get a repeater set up for my project but have been having trouble making adjustments for it to work with my deploy system.  I was able to adapt the loader and mutator since i can download the zip files in bintray at https://bintray.com/snowplow/snowplow-generic/snowplow-bigquery-loader#files/ but i noticed that the repeater is not listed there.

**Comment by benjben** [comment]
Hi @blackknight467, thank you for reporting this. You're right that our Travis configuration is missing the publishing of the zip for the repeater. We've created #120 to take care of it.

All the artifacts for BigQuery loader are also published as Docker images on our Docker registry (waiting for the switch to Docker Hub). You will find the repeater [here](https://bintray.com/snowplow/registry/snowplow%3Asnowplow-bigquery-repeater).
