### ISSUE TITLE
Repeater: publish zip artifact to Bintray

### ISSUE THREAD

**Issue by benjben** [snowplow-incubator/snowplow-bigquery-loader#120]
Contrary to the actual loader and to the mutator, the zip with the repeater is not pushed to Bintray.

Needs to be added [here](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/.travis/release.yml#L38-L57).

Reported in #119.

**Comment by blackknight467** [comment]
Stream loader seems to be missing from that as well.

**Comment by dilyand** [comment]
See: #73
