### ISSUE TITLE
StreamLoader: improve performance

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-bigquery-loader#134]
There a lot of decisions we've made hastily:

* Concurrency factor exceeding amount of available CPU is a source of a lot of unnecessary context switches: [1](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/streamloader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/streamloader/Resources.scala#L69), [2](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/streamloader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/streamloader/StreamLoader.scala#L50)
* In `goodSink` only insertion should be shifted off to a blocking thread pool [(we shift the whole `insert` action and `ack`)](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/streamloader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/streamloader/Bigquery.scala#L35)
* We use default parallel pull count provided by `PubsubGoogleConsumerConfig`, which defaults to 3
* It's much easier to control local cache without Dataflow: https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/107

**Comment by dilyand** [comment]
Superseded by https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/192
