### ISSUE TITLE
Common: add sbt-assembly

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-bigquery-loader#135]
We're publishing assets just as Docker images, but some users need fatjars. It would be great to make it possible for them to build fatjars themselves with one-two simple commands without knowledge of sbt/Scala.

**Comment by chuwy** [comment]
We should put it to GH assets, not on S3 or GCS. Example: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/.github/workflows/deploy_tracker.yml#L82-L101

**Comment by dilyand** [comment]
Superseded by https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/149.
