### ISSUE TITLE
Switch Forwarder to using subscription

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-bigquery-loader#15]

**Comment by camerondavison** [comment]
I see some commits for this issue, but it seems like [rc10]( https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/0.2.0-rc10/forwarder/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/forwarder/Forwarder.scala#L40) is still using the topic. Even though [rc9](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/0.2.0-rc9/forwarder/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/forwarder/Forwarder.scala#L43) is using the subscription, not sure if that was on purpose. it seems like there are bunches of commits attached to the rc tags that are not in the `origin/release/0.2.0` branch. I am not sure how y'all are managing this project in git.

**Comment by chuwy** [comment]
Hi @camerondavison, sorry I missed your comment back then. We had this fix in `release/0.1.1` branch, but then got switched to a different approach with app called Repeater ([more details](https://discourse.snowplowanalytics.com/t/bigquery-loader-0-2-0-released/3563) on our discourse). Now Forwarder is also fixed in 0.3.0 (but we actively considering a deprecation plan for it).
