### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-bigquery-loader#2]
* `BINTRAY_SNOWPLOW_GENERIC_USER` (unencrypted?)
* `BINTRAY_SNOWPLOW_GENERIC_API_KEY`

Important note: we'll be publishing tar.gz archives with executables there, not fatjar, because scio/beam does not work with sbt-assembly.

Probably we'll also need docker registry credentials as me and @BenFradet thinking about using sbt-native-packager (?) and its Docker integration and publish an image straight away.

**Comment by BenFradet** [comment]
>Probably we'll also need docker registry credentials as me and @BenFradet thinking about using sbt-native-packager (?) and its Docker integration and publish an image straight away.

yes we'll draft something this week
