### ISSUE TITLE
[Docker] Streamloader logs missing 

### ISSUE THREAD

**Issue by ianarsenault** [snowplow-incubator/snowplow-bigquery-loader#231]
When I run docker container using `snowplow/snowplow-bigquery-streamloader:1.0.0` with `info` level there are no logs displayed when messages fail or successfully insert into big query

**Steps to reproduce**

```bash
docker run \
    -d \
    --restart always \
    --network host \
    --name bq_streamloader \
      --log-driver gcplogs \
    -e 'JAVA_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=info' \
    snowplow/snowplow-bigquery-streamloader:1.0.0 \
    --config=${config_b64} \
    --resolver=${iglu_resolver_b64}
```

`docker logs -t -f bq_streamloader` will not show any logs for success or failure

**Comment by spenes** [comment]
You are right @ianarsenault, thanks for reporting. It will be implemented under https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/238. Closing this one.
