### ISSUE TITLE
How do you actually run snowplow-bigquery-loader?

### ISSUE THREAD

**Issue by jrStaff** [snowplow-incubator/snowplow-bigquery-loader#25]
I don't know how to create an executable on of the git repo? I am clearly missing something but after cloning and calling the given:
```
./snowplow-bigquery-loader \
    --config=$CONFIG \
    --resolver=$RESOLVER
```
It doesn't find it, which makes sense because I don't see this.

**Comment by chuwy** [comment]
Hi @jrStaff, please direct support questions to our forumns http://discourse.snowplowanalytics.com/. Our github is for bugreports and feature requests only. Thanks!
