### ISSUE TITLE
Create option to run jobs asynchronously

### ISSUE THREAD

**Issue by benney-au-le** [snowplow-incubator/snowplow-bigquery-loader#262]
Currently the code has a hard coded `sc.run().waitUntilFinish(Duration.Inf)`.
https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/modules/loader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/loader/Main.scala#L25

When we start our dataflow jobs as part of the deployment pipelines 
The docs recommends running the stream-loader from docker like this 
```
docker run --rm \
    -e GOOGLE_APPLICATION_CREDENTIALS=/gcloud/application_default_credentials.json \
     --mount type=bind,source=$HOME/.config/gcloud,target=/gcloud,readonly \
    snowplow/snowplow-bigquery-loader:1.2.0 \
    --runner=DataFlowRunner \
    --project=myproject \
    --region=australia-southeast1 \
    --resolver=$(cat $PWD/config/resolver.json | base64 -w 0) \
    --config=$(cat $PWD/config/config.hocon | base64 -w 0)
```

However this blocks execution indefinitely since the pipeline this is a streaming job that is running forever.
What is the recommended way to run and deploy these dataflow jobs?

**Comment by dilyand** [comment]
Hi @benney-au-le , this is not really a bug. Could you please consider posting this question to our [Discourse forum](https://discourse.snowplowanalytics.com/)? You'll be able to get better advice on this there.
