### ISSUE TITLE
Stream loader: Fix metrics when an insert has no successful rows

### ISSUE THREAD

**Issue by istreeter** [snowplow-incubator/snowplow-bigquery-loader#302]
We got this exception on a pipeline:

```
UnsupportedOperationException empty.min
```

It's coming from [this line](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/1.4.1/modules/streamloader/src/main/scala/com/snowplowanalytics/snowplow/storage/bigquery/streamloader/Bigquery.scala#L109) and it's because calling `.min` on a list is an unsafe operation in scala.  The list could be empty.

**Comment by dilyand** [comment]
Getting this exception also results in the app getting killed via SIGINT:

```
[io-compute-12] INFO com.snowplowanalytics.snowplow.storage.bigquery.streamloader.Shutdown - Source of events was cancelled
```
