### ISSUE TITLE
streamloader healthcheck non-functional?

### ISSUE THREAD

**Issue by ssuhre** [snowplow-incubator/snowplow-bigquery-loader#324]
Hi,

we are using the snowplow-bigquery-streamloader:1.5.2 container image in Kubernetes and are trying to figure out how to set up a livenessProbe. We assumed the [configuration reference](https://docs.snowplow.io/docs/pipeline-components-and-applications/loaders-storage-targets/bigquery-loader/snowplow-bigquery-loader-configuration-reference/) meant that enabling the dropwizward configuration would enable an HTTP endpoint for metrics and health checking but the settings did not seem to have any effect. Are we missing something? Is the configuration meant for something else than the streamloader?

**Comment by benjben** [comment]
Hi @ssuhre,

Dropwizard metrics were for the [Dataflow](https://cloud.google.com/dataflow) variant of the loader, which we [deprecated](https://github.com/snowplow-incubator/snowplow-bigquery-loader/commit/69fce2e4375c85955a72d0a7e5ab9eaf88a62d21) recently. We had forgotten to update the docs, sorry about that, thank you for reporting it, it's fixed now ([PR](https://github.com/snowplow/documentation/pull/288)).
