### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBind er".

### ISSUE THREAD

**Issue by Prabhat-ch** [snowplow-incubator/snowplow-bigquery-loader#36]
SLF4J: Defaulting to no-operation (NOP) logger implementation

**Comment by shadiramadan** [comment]
When launching the mutator for example:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
http://www.slf4j.org/codes.html#StaticLoggerBinder

SL4J needs a logging backend.

https://github.com/lightbend/scala-logging

**Comment by spenes** [comment]
In the current version logging backend library `log4cats-slf4j` is [only dependency of `repeater`](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/master/build.sbt#L104). However, [in the new version](https://github.com/snowplow-incubator/snowplow-bigquery-loader/pull/184), it will be [dependency of `common` module](https://github.com/snowplow-incubator/snowplow-bigquery-loader/blob/feature/o11y/build.sbt#L37), therefore it will solve this problem for all modules.
