### ISSUE TITLE
Attach a loading timestamp

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-bigquery-loader#38]
The most reliable way is to try to achieve it as a SQL function, but doesn't look like streaming inserts provide this kind of API.

**Comment by dilyand** [comment]
What would this loading timestamp be used for?

**Comment by dilyand** [comment]
Answering my own question: an "inserted at" timestamp column in BigQuery can make it easier to identify rows loaded since the data model was last run.

**Comment by dilyand** [comment]
Superseded by https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/140
