### ISSUE TITLE
Mutator: does not allow for `-` and `_` in base64 encoded JSON

### ISSUE THREAD

**Issue by peel** [snowplow-incubator/snowplow-bigquery-loader#65]
We are using `Base64.getDocoder().decode` which does not allows for mentioned characters.
We should investigate using `Base64.getUrlDocoder().decode` which would allow for these.

source: https://discourse.snowplowanalytics.com/t/illegal-base64-character-when-running-bigquery-mutator-with-docker/3662

**Comment by chuwy** [comment]
That's interesting. I'm very sure that we always use `_` and `-` characters inside configs.

**Comment by AlexanderIgorovych** [comment]
I got the bigquery_config.json file from https://github.com/snowplow-incubator/snowplow-bigquery-loader/wiki/Setup-guide

And the iglu_configuration (taken from here https://github.com/snowplow/iglu/wiki/Iglu-client-configuration) also uses `-`

**Comment by peel** [comment]
In fact that might be related to how the string was encoded rather than how it is decoded. If it was encoded as url-encoded it might not go through and cause above characters to fail.
