### ISSUE TITLE
Mutator: handle exception that can be thrown when getting table

### ISSUE THREAD

**Issue by dilyand** [snowplow-incubator/snowplow-bigquery-loader#91]
When we call `client.getTable` In `TableReference.scala`, it can throw an exception. We currently only handle `null` and a returned table.

**Comment by chuwy** [comment]
I think the problem we stumbled upon was a NPE? Or what exceptions we should handle here?

**Comment by dilyand** [comment]
`getTable` can throw a `BigQueryException`, which we are not prepared for.

This ticket is "inspired" by the NPE, but not directly addressing it.

**Comment by chuwy** [comment]
Been talking to @spenes and we just realised that catching the exception is not much better than just throwing it since we cannot do anything with it anyway, just rethrow.

Feel free to close or elaborate if I'm missing something.
