### ISSUE TITLE
Bump log4cats-slf4j to 1.0.1

### ISSUE THREAD

**Issue by dilyand** [snowplow-incubator/snowplow-bigquery-loader#95]

**Comment by chuwy** [comment]
I think this one will bring cats 2 and co. so would be careful about it.

**Comment by dilyand** [comment]
It didn't break compilation. Do you think it's better to stick with 0.3.0 until we upgrade cats?

**Comment by dilyand** [comment]
Checked the dependency tree and it does indeed bring cats 2.0.0. Nothing seems to be breaking but I'll remove it from the 0.5.0 milestone and we can do it when we bump cats.

**Comment by chuwy** [comment]
Cats 2.0 should generally be safe, but I'm still keen to move the whole ecosystem to cats 2.0 at once.

**Comment by chuwy** [comment]
> It didn't break compilation. Do you think it's better to stick with 0.3.0 until we upgrade cats?

They're source-compatible, but binary-incompatible which means the problem we might hit is the unexpected runtime exception (such as `NoSuchMethodError`)

**Comment by dilyand** [comment]
There is no official 0.4.0, just `M1` and `M2`. Anyway, I dropped it from 0.5.0.
